version: '3.8'

services:
  sudoku-app:
    build: .
    container_name: sudoku-book-app
    restart: unless-stopped
    ports:
      - "8080:80"
    # Opcional: Si necesitas pasar variables de entorno
    # environment:
    #   - NODE_ENV=production
